import { UserInfo } from "@/pages/Profile/UserInfo";

async function getProfileData() {
  try {
    const response = await fetch(
      "https://checkinsta.herokuapp.com/check_upk/camillecerf?get_posts=true"
    );

    if (!response?.ok) {
      return null;
    }

    const data = await response.json();

    return data;
  } catch (error) {
    return null;
  }
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Home() {
  const profileData = await getProfileData();
  console.log(profileData);

  return (
    <main className="flex flex-col min-h-screen">
      <div className="px-5 pt-8 md:max-w-[930px] md:mx-auto mb-8">
        <UserInfo user={profileData?.user} profileData={profileData} />
      </div>
    </main>
  );
}
