import { Posts } from "@/pages/Profile/Posts";
import { UserInfo } from "@/pages/Profile/UserInfo";

async function getProfileData() {
  try {
    const response = await fetch(
      "https://checkinsta.herokuapp.com/check_upk/camillecerf?get_posts=true"
    );

    if (!response?.ok) {
      return null;
    }

    const data = await response.json();

    return data;
  } catch (error) {
    return null;
  }
}

export const metadata = {
  title: "Mini instagram profile",
  description: "Generated by create next app",
};

export default async function Home() {
  const profileData = await getProfileData();

  return (
    <main className="flex flex-col min-h-screen">
      <div className="px-5 pt-8 md:max-w-[930px] md:mx-auto mb-8">
        <UserInfo user={profileData?.user} profileData={profileData} />

        <div className="pt-8 border-t border-gray-500 border-solid lg:mt-16 lg:pt-12">
          <Posts posts={profileData?.posts?.items} />
        </div>
      </div>
    </main>
  );
}
